version: '3'

services:
  gunicorn:
    build: .
    image: gunicorn:20.1.0
    container_name: gunicorn
    volumes:
      - .:/work
      - gunicorn:/var/run/gunicorn
      - ./media:/work/media
  nginx:
    image: nginx:1.17.7
    container_name: nginx
    depends_on:
      - gunicorn
    ports:
      - "9001:9001"
    volumes:
      - ./conf.d:/etc/nginx/conf.d
      - gunicorn:/var/run/gunicorn
      - ./media:/work/media
volumes:
  gunicorn:
    driver: local