# Generated by Django 4.1.2 on 2022-11-15 04:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_user_use_system'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='char_img_ids',
            field=models.CharField(default='0,1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20,21,22,23,24,25,26,27,28,29', max_length=80),
        ),
    ]
