# Generated by Django 4.1.2 on 2022-11-15 05:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_user_char_img_ids'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='num_finished_img',
            field=models.ImageField(default=0, upload_to=''),
        ),
    ]
