# Generated by Django 4.1.2 on 2022-11-15 05:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_user_num_finished_img'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='num_finished_img',
            field=models.IntegerField(default=0),
        ),
    ]
