# Generated by Django 4.1.2 on 2022-10-19 02:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('img_processing', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('path', models.CharField(max_length=2)),
                ('img', models.ImageField(upload_to=models.CharField(max_length=2))),
            ],
        ),
    ]
