# Generated by Django 4.1.2 on 2022-10-19 03:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('img_processing', '0002_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='image',
            old_name='path',
            new_name='img_id',
        ),
        migrations.AlterField(
            model_name='image',
            name='img',
            field=models.ImageField(upload_to='estimated/<django.db.models.fields.CharField>/'),
        ),
    ]
