# Generated by Django 4.1.2 on 2022-10-20 14:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('img_processing', '0004_alter_image_img_questionnaire'),
    ]

    operations = [
        migrations.AlterField(
            model_name='questionnaire',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
        ),
    ]
