# Generated by Django 4.1.2 on 2022-11-15 06:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('img_processing', '0005_alter_questionnaire_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='imageprocessing',
            name='use_system',
            field=models.BooleanField(default=True),
        ),
    ]
