# Generated by Django 4.1.2 on 2022-11-18 08:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('img_processing', '0006_imageprocessing_use_system'),
    ]

    operations = [
        migrations.RenameField(
            model_name='questionnaire',
            old_name='usability',
            new_name='system_usability',
        ),
        migrations.AddField(
            model_name='questionnaire',
            name='system_is_better',
            field=models.BooleanField(default=True),
        ),
    ]
