# Generated by Django 4.1.2 on 2022-11-18 08:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('img_processing', '0007_rename_usability_questionnaire_system_usability_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='questionnaire',
            name='system_is_better',
        ),
    ]
